# Generated by Django 2.2.3 on 2019-07-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('nivel', models.IntegerField()),
                ('tips', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
