# Generated by Django 2.2.3 on 2019-07-20 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendientes', '0002_auto_20190720_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuestas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_idea', models.CharField(max_length=100)),
                ('numero_idea', models.IntegerField()),
                ('calificacion', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendientes.Pregunta')),
            ],
        ),
    ]
